version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - npm prune --production
  post_build:
    commands:
      - zip -r build.zip .
      - aws s3 cp build.zip s3://alpha-store-bucket/build.zip
artifacts:
  files:
    - build.zip
