version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building Next.js app...
      - npm run build
  post_build:
    commands:
      - echo Creating deployment archive...
      - mkdir deployment-package
      - mv .next deployment-package/
      - cp -r . deployment-package/ (exclude .git folder)
      - zip -r deployment-package.zip deployment-package
